service: pdf-generator-api

# Adopt behaviour in next version
useDotenv: true
variablesResolutionMode: "20210219"

provider:
  name: aws
  runtime: nodejs12.x
  region: ${env:AWS_BUCKET_REGION}
  stage: ${opt.stage,'dev'}

  # Adopt behaviour in next version
  lambdaHashingVersion: "20201221"
  apiGateway:
    shouldStartNameWithService: true

  logs:
    restApi: true
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:GetObject
            - s3:GetObjectAcl
            - s3:PutObject
            - s3:PutObjectAcl
          Resource: "arn:aws:s3:::${self:custom.bucket}/*"
        - Effect: Allow
          Action:
            - s3:ListBucket
          Resource: "arn:aws:s3:::${self:custom.bucket}"

plugins:
  - serverless-offline
  - serverless-dotenv-plugin
  - serverless-plugin-typescript-express
  - serverless-domain-manager

custom:
  bucket: ${env:S3_BUCKET_NAME}
  serverless-offline:
    noPrependStageInUrl: true
  customDomain:
    domainName: api.docforest.eu
    basePath: ''
    stage: 'prod'
    createRoute53Record: true
    certificateName: 'docforest.eu'
    autoDomain: true

package:
  exclude:
    - ./**
    - '!dist/**'
    - '!node_modules/**'

functions:
  generator:
    handler: src/generator.handler
    memorySize: 800
    events:
      - http:
          path: generate/from_html
          method: get
          cors: true
      - http:
          path: generate/from_html
          method: post
          cors: true
      - http:
          path: generate/from_template
          method: get
          cors: true
      - http:
          path: generate/from_template
          method: post
          cors: true
  api:
    handler: src/server.handler
    memorySize: 256
    events:
      - http:
          path: auth/login
          method: post
          cors: true
      - http:
          path: templates
          method: get
          cors: true
      - http:
          path: templates
          method: delete
          cors: true
      - http:
          path: templates/upload_url
          method: get
          cors: true
      - http:
          path: files
          method: get
          cors: true
      - http:
          path: files
          method: delete
          cors: true
      - http:
          path: fonts
          method: get
          cors: true
      - http:
          path: fonts
          method: delete
          cors: true
      - http:
          path: fonts/upload_url
          method: get
          cors: true

