name: Deploy API

on:
  push:
    paths-ignore:
      - 'web/**'
      - 'infrastructure/**'
      - '.github/**'
      - '!.github/workflows/deploy-api.yml'
    branches:
      - master

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Yarn Install
        run: |
          yarn install
        working-directory: api
      - name: serverless deploy
        run: |
          touch api/.env.local.production
          echo "USER_DATA=$USER_DATA" >> "api/.env.production.local"
          echo "JWT_SECRET=$JWT_SECRET" >> "api/.env.production.local"
          echo "UUID_NAMESPACE=$UUID_NAMESPACE" >> "api/.env.production.local"
          yarn api deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_MASTER_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_MASTER_SECRET_ACCESS_KEY }}
          USER_DATA: ${{ secrets.USER_DATA }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          UUID_NAMESPACE: ${{ secrets.UUID_NAMESPACE }}

