name: API Unit Tests
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Yarn Install
      run: |
        yarn install
    - name: Typescript check
      run: |
        yarn test:compile
    - name: Unit tests
      run: |
        yarn test
