name: Tests
on:
  pull_request:
  push:
    paths-ignore:
      - 'infrastructure/**'
      - '.github/**'
      - '!.github/workflows/tests.yml'
    branches:
      - master
      - beta
jobs:
  test:
    runs-on: ubuntu-latest
    container: node:14
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres_pass
          POSTGRES_DB: vailable_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Get yarn cache directory path
      id: yarn-cache-dir-path
      run: echo "::set-output name=dir::$(yarn cache dir)"
    - uses: actions/cache@v2
      id: yarn-cache # use this to check for `cache-hit`
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-
    - name: Yarn Install
      run: |
        yarn install
    - name: Typescript check
      run: |
        yarn test:compile
    - name: Unit tests
      run: |
        yarn test:all
    - name: Upload codecov
      uses: codecov/codecov-action@v1
      with:
        flags: api
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./api/coverage/coverage-final.json
    - name: Upload codecov
      uses: codecov/codecov-action@v1
      with:
        flags: web
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./web/coverage/coverage-final.json
    - name: Upload codecov
      uses: codecov/codecov-action@v1
      with:
        flags: backend
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./backend/coverage/coverage-final.json
    - name: Upload codecov
      uses: codecov/codecov-action@v1
      with:
        flags: sdk
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./sdk/coverage/coverage-final.json
    - name: Upload codecov
      uses: codecov/codecov-action@v1
      with:
        flags: shared
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./shared/coverage/coverage-final.json
